### ISSUE TITLE
"Letzte Änderung: Datum Uhrzeit" wird nicht mehr angezeigt und fehlerhaft importiert

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/studio-lite#115]
Diese Anzeige war in der alten Studioversion unter Eigenschaften verfügbar (und sehr nützlich), in der neuen nicht.

Exportiert man eine Unit aus dem alten Studio und importiert sie ins Neue, so erscheint die Info in der Notiz
vgl. Screenshot
![grafik](https://user-images.githubusercontent.com/78726636/193069314-62ff9135-a76f-4c27-b481-2d04d09fb597.png)

tw. aber auch fehlerhaft bzw. unverständlich
aus "Letzte Änderung: 26.07.2022 18:18" https://www.iqb-teststudio.de/#/a/135/u/3267
wurde "2022-07-26T16:18:35+00:00" https://www.iqb-studio.de/#/a/31/114/metadata

**Comment by tobhu1981** [comment]
Mit mehreren Aufgaben probiert. Zeitstempel wird richtig angezeigt. Dieser erscheint jetzt auch nicht mehr unter "Beschreibungen", sondern befindet sich unterhalb des Schemermoduls.
