### ISSUE TITLE
Sortierung der Aufgaben innerhalb einer Studie/Bereich nicht nach Gruppennamen

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/studio-lite#120]
Derzeit steht diejenige Gruppe ganz oben in der Unitsliste, in welcher die alphabetisch bzw. numerisch kleinste benannte Unit enthalten ist, nicht diejenige Gruppe die den alphabetisch bzw. numerisch kleinsten Namen hat
Hier ein Beispiel: 
![grafik](https://user-images.githubusercontent.com/78726636/193300512-d8ffcf3e-9226-4cf6-8fb4-77e3ad2b2846.png)

Es steht nicht die Gruppe "01_Vorlagen" in der Liste ganz oben, sondern die Gruppe "02_Hörverstehen", da diese Units beginnend mit "C" enthält im Gegensatz zur Vorlagengruppe die Units beginnend mit "H" enthält und C vor H im Alphabet kommt...

Die Benennung der Gruppennamen sollen bitte entscheidend für die Position in der Liste sein

**Comment by tobhu1981** [comment]
funzt!
