### ISSUE TITLE
Unit-Xml: Manche Attribute können vom TC nicht angenommen

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/studio-lite#156]
Das Studio erzeugt eine Reihe von neuen Attributen und Elementen in der Unit-Xml.
Diese verhindern aktuell, dass die Unit in das Testcenter in der aktuellsten Version: 13alpha auf dem Testserver geladen werden kann.

![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/b6e00891-c955-4a47-a8b6-4531974b6b22)

Ich schätze mal Philipp muss da auf seiner Seite anpassen. Bei den BaseVariablen bin ich mir da sicher, gehört ja zum Schemer und ist daher neu. Bei dem Attribut: LastChange in DefintionRef und in den Metadaten bin ich mir da nicht so sicher. Muss Philipp hier nachbessern oder musst du da @Martin nachbessern.

**Comment by paflov** [comment]
Wird ab Tetst-Studio 13 gehen. In der momentanten beta noch nicht, aber in der nächsten.

**Comment by mechtelm** [comment]
Das ist mit dem TC-Release Anfang November gelöst. Bis dahin bitte manuell nachfummeln. Es bekommen dann beide Produktivsysteme iqb-testcenter.de und iqb-fragebogen.de das Update.

**Comment by tobhu1981** [comment]
In neuer Testcenter Version: 13.0.0-RC3 getestet. Funktioniert soweit

**Comment by tobhu1981** [comment]
In neuer Testcenter Version: 13.0.0-RC3 getestet. Funktioniert soweit
