### ISSUE TITLE
Unitliste zeigt eine Nummer (vmtl. index) obwohl kein Name vergeben ist

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/studio-lite#163]
Aktuell:
Screenshot anbei. man sieht den Tooltip "11", obwohl keine Name dran ist.

Erwartet:
Entweder kein Tooltip oder mit Hinweis, das kein Name existiert oder sowas.

![tooltip](https://user-images.githubusercontent.com/446878/196437009-5a4ab6d4-2b3b-4a33-b21e-4a522f7e519c.png)

**Comment by tobhu1981** [comment]
Da musst du mir auf die Sprünge helfen, im Moment verstehe ich den Sinn dieses Toolitps an der Stelle noch nicht. In der aktuellen Version: 2.3.0-rc.2 wird dort jetzt immer der in den Eigenschaften gesetzte "Name" angezeigt.

**Comment by rhenck** [comment]
> 

Das ist ja gerade der Punkt, wenn kein Name da ist, wird da eine Zahl angezeigt, die man nicht versteht.

**Comment by mechtelm** [comment]
Nee habbich geändert. Richard beschreibt einen Fehler, der behoben wurde.

**Comment by rhenck** [comment]
Dann mach doch das Ticket zu?! :)

**Comment by tobhu1981** [comment]
funzt. Wird nur angezeigt wenn ein "name" vergeben ist.
