### ISSUE TITLE
Export: GeoGebra

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/studio-lite#202]
Im Moment wird keine zugehörige GeoGebra-Datei mit zu einer Aufgabe mit GeoGebra-Element ausgegeben. Das entsprechende GeoGebra-Element kann daher aktuell im Testcenter nicht dargestellt werden.

**Comment by jojohoch** [comment]
Hier lag vermulich ein anderer Fehler vor. Prinzipiell können Units mit Geogebra-Aufgaben im Testcenter dargesstellt werden
