### ISSUE TITLE
Export: Ausgabebezeichner Player nicht gleich wie Aspect Releases

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/studio-lite#203]
Bei Ausgabe im Studio heißt der Player: iqb-player-aspect@x.xx.x.html, im Repo: Aspect-Module unter Releases heißt er: verona-player-aspect-x.xx.x.html. Falls der Player direkt aus dem Repo verwendet wird, müsste entweder der Playername geändert werden oder der Bezeichner des Players in der Unit-Xml.

**Comment by tobhu1981** [comment]
2.4.1: Bezeichner Player bei aktuelle Ausgabe durch das Studio:
![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/0444adf2-9527-462f-a878-c7d3d90edc04)
Hier ist also immer noch das @ drin und in den Repo Releases nicht. Weiß aber gar nicht, ob das jetzt überhaupt noch ein Problem darstellt, weil das Testcenter jetzt nur noch auf den in der Player-Html hinterlegten Bezeichner schaut und nicht mehr auf den Dateinamen. Aber klar wenn es gleich ist machen wir sicherlich nichts verkehrt...oder?

**Comment by jojohoch** [comment]
Das ist richtig so. Hier handelt es sich um die ID. Die Id ist mit @, der Dateiname mit -
