### ISSUE TITLE
Aufgabenfolgen: Infoleiste: Metadaten

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/studio-lite#214]
Optimierungsvorschlag: Auch die Metadaten farblich kennzeichnen?
![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/7ad59acd-8bf2-433c-ae95-413287962d1d)

**Comment by jojohoch** [comment]
es wurde stattdessen die Darstellung des Prints übernommen
