### ISSUE TITLE
Voreinstellungen für Studien bzgl. Editor/Player/Schemer

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/studio-lite#224]
In der Box für die Festlegung der Voreinstellungen für Editor/Player/Schemer kann ich derzeit "nur" einen festen Editor/Player/Schemer bestimmen. Wir würden aber in bestimmten Phasen/Arbeitsbereichen gern immer Aufgaben mit der jeweils aktuellsten Version anlegen, egal ob vorher angelegte Aufgaben noch mit einer ältere Version angelegt wurden. Wenn man nun diese Einstellungen erweitern könnte um eine Option, "Neue Aufgaben immer mit der neusten  Editor/Player/Schemer" anlegen, wäre das leichter. So müssten wir nicht alle Bereiche die wir als "Poweruser" verwalten bei der Veröffentlichung eines neuen Editor/Player/Schemer auf die jeweils neuste Version umstellen. 
![grafik](https://user-images.githubusercontent.com/78726636/200604036-fec3179e-d3a3-48df-bd03-84db0ef861c8.png)

**Comment by mechtelm** [comment]
Abgelehnt. Die Gefahr, dass man sich unerwünschte Effekte einfängt, ist zu groß. Besser: Umstellung aller Units eines Arbeitsbereiches auf die jeweils aktuellste Version mit einem Klick/Menüpunkt.
