### ISSUE TITLE
wenn Name der Aufgabenfolge zu lang, ungünstige Darstellung in den Detaileinstellungen dazu 

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/studio-lite#225]
siehe Screenshot
![grafik](https://user-images.githubusercontent.com/78726636/200866102-b807b323-08fe-4db8-b9c0-02ef4ba7581a.png)

**Comment by tobhu1981** [comment]
**2.4.1**
Ist leider immer noch so:
![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/df83ee76-7582-4d80-8895-086e2730461e)

**Comment by jojohoch** [comment]
hier habe ich einen anderen Bug gefixt.
