### ISSUE TITLE
Farbkontraste bei nicht nutzbarem Kommentarsymbol/Navigationspfeil in Aufgabenfolgen

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/studio-lite#228]
wenn man noch keine Kommentare abgeben kann oder noch nicht zurück gehen kann, sind die Symbole "ausgegraut" - aber im Kontrast mit dem Hintergrund eigentlich gar nicht mehr erkennbar. Das ist nicht ganz intuitiv verständlich...

![grafik](https://user-images.githubusercontent.com/78726636/201139441-3c1061a8-5ca1-4c1f-a19d-682a237ee899.png)

**Comment by jurei733** [comment]
@jojohoch @jurei733 finden die Ausgestaltung in Ordnung
