### ISSUE TITLE
Verwerfen von Änderungen --> voeStartCommand

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/studio-lite#268]
Wenn die Änderungen im Editor verworfen werden, dann sollte der Editor die vorherige Version der Definition über ein neues voeStartCommand bekommen.

**Comment by jurei733** [comment]
voeStartCommand wird aktuell beim Verwerfen der Editor Änderungen erneut aufgerufen mit der vorherigen Version der Definition.
