### ISSUE TITLE
Counter beim Löschen von Modulen wird nicht zurückgesetzt

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/studio-lite#279]
Wenn man Dateien löscht, sagt er beim ersten Mal die korrekte Anzahl und bei weiteren Löschaktionen wird die Anzahl der ausgewählten Dateien einfach addiert.

**Comment by tobhu1981** [comment]
Hier ist mir nicht ganz klar welcher Counter gemeint ist. Könnt ihr das noch einmal genauer aufzeigen?
