### ISSUE TITLE
Production needs git

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/studio-lite#39]
Ist unklar warum man auf prod git brauchen sollte. Ich habe einmal "git init" ausgeführt, das scheint zu reichen, sollte aber nicht nötig sein.

**Comment by mechtelm** [comment]
Dieses Ticket verstehe ich nicht - könntet Ihr bitte klären?

**Comment by svwolter** [comment]
README wurde bereits am 27. Juli aktualisiert. Es wird keine Git-Installation auf Production benötigt! Schließe nun das Ticket.
