### ISSUE TITLE
Falsche Unit/Workspace Zuordnung (nach Verschieben?)

### ISSUE THREAD

**Issue by jojohoch** [iqb-berlin/studio-lite#439]
Dieser Link https://www.iqb-studio.de/#/a/31/203/preview führt zu einer Unit, die in der Liste der Units auf der linken Seite nicht auftaucht. In der Vergangenheit wurde die Unit verschoben.

**Comment by mechtelm** [comment]
Muss zu 404 führen

**Comment by jojohoch** [comment]
Da Reviews ebenfalls auf die UnitDefinition zugreifen können müssen, erscheint ein Zugriff (zumindest in diesem Fall) ohne Überprüfung der WotkspaceId weiterhin sinnvoll
