### ISSUE TITLE
Admin: Xlsx Report Module buggy

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/studio-lite#445]
Die Excel-Datei, die man im Admin-Bereich als Bericht der Arbeitsbereiche (Module) runterladen kann, hat eine Spalte "Letzte Änderung". Diese Spalte enthält ungültige Datumswerte.

**Comment by jurei733** [comment]
Bei Testen der Export Funktionalität sind die Datumswerte in der Spalte "Letzte Änderung" korrekt formatiert. Das Problem scheint bereits gelöst zu sein.

**Comment by mechtelm** [comment]
Heute exxportiert:
IfBQ | 37 | VERA 2023 Deutsch | 98 | 00.04.2023
Silke | 2 | Geogebra | 43 | 00.05.2023
Probierbereich | 15 | 01_Vorlagen | 29 | 01.00.2023
Sandboxes | 6 | Mechtel: Abi-Player | 85 | 01.00.2023

**Comment by jurei733** [comment]
Fehlerhafte Datumsangabe erscheint wenn in einem Arbeitsbereich keine Unit enthalten ist.
