### ISSUE TITLE
Probleme im UpdateScript

### ISSUE THREAD

**Issue by jojohoch** [iqb-berlin/studio-lite#458]
- Beim Update von 4.0.0 auf 4.1.0 konnte das Updatescript keine Verbindung zu github aufbauen. Abhilfe schaffte die  Änderung der curl Befehle zu curl -k.
- Beim Herunterfahren von traefik blieb das Netzwerk bstehen. Hierdurch gelang es nicht traefik erneut zu starten. (Mögliche Ursache  hierfür war, dass zunächst traefik und dann erst studio-lite heruntergefahren wurde.)
- Es wäre hilfreich, die Angabe welche Dateien miteinander verglichen werden sollen durch eine Zeile "diff a.. b.." zu ergänzen

**Comment by svwolter** [comment]
* Verbindungsproblem lag vermutlich am GitHub-Host. curl -k als einmalige Hilfe ok, schaltet aber die Überprüfung der Zertifikate aus, daher an dieser Stelle keine Änderung de Update-Skriptes.
* Netwerk muss bestehen bleiben, solange die Studio-Anwendung läuft. Das erneute Hochfahren von Traefik wird dadurch nicht verhindert. Problem konnte nicht nachgestellt werden.
* Ausgaben des Update-Skriptes wurden in  #467 überarbeitet.
