### ISSUE TITLE
Erzeugen von Logins bei Studio-Export

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/studio-lite#492]
Seit dem letzten Update wird nicht mehr beschriftet, ob die erzeugten Logins für Testtaker oder Review sein sollen.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcEptIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e424cde637e20a5f8e3b84c2dfebec254ec3d1fe/grafik.png)

**Comment by jurei733** [comment]
An dieser Stelle gelten die Logins für die Testtaker Einstellungen.
Soll eine weitere Kategorie mit Review Einstellungen erscheinen?
Für welchen Anwendungsfall wird die Unterscheidung benötigt?

**Comment by jkoelm** [comment]
Im Bild sind ja drei Felder, in die man Zahlen eintragen kann. Man konnte dort vorher Logins für Testtaker und für Review erstellen lassen (wofür das dritte Feld ist, weiß ich gerade nicht mehr). Auf jeden Fall sind diese Felder jetzt nicht mehr beschriftet, d. h. man weiß nicht, für was man die Zahlen einträgt.

**Comment by jurei733** [comment]
"Anzahl für Review",
"Anzahl für Monitor",
"Anzahl für Test",

So sollten die Platzhalter Beschriftungen sein von oben nach unten.
