### ISSUE TITLE
Gewählte Unit im Export-Dialog (vor)auswählen

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/studio-lite#561]
Steps:
- Unit auswählen
- Export-Dialog öffnen

Aktuelles Verhalten:
- Keine unit ist im Dialog ausgewählt und man muss ggf. lange rumscrollen oder sich die ID der Unit gemerkt haben und nach ihr filtern

Erwartetes Verhalten:
- Unit ist ausgewählt und bereit exportiert zu werden

**Comment by jurei733** [comment]
Die Export Funktion sowie alle weiteren Funktionen '...' beziehen sich auf alle Units (Unit-Liste), so entspricht erwartbaren Verhalten.

**Comment by rhenck** [comment]
Das finde ich doch sehr unbefriedigend... Wenn das so funktioniert, wie es soll, darf ich dann einen Feature-Request stellen für ein neues Feature, um die Möglichkeit zu haben die ausgewählte Aufgabe zu exportieren? ;)
