### ISSUE TITLE
Ändern des Profils einer Aufgabe

### ISSUE THREAD

**Issue by nanoyan** [iqb-berlin/studio-lite#613]
Eine Aufgabe mit Profil A war es, zu Profil B zu wechseln. Der Task migriert Informationen von Profil A nach Profil B, was nicht erwünscht ist.

**Comment by jurei733** [comment]
Die eigentlichen Daten werden nicht migriert bei Profilwechsel lediglich die tabellarische Ansicht der Aufgaben Metadaten passt nicht in diesem Fall. Die Aufgaben Metadaten Items werden bei Profilwechsel korrekt angezeigt,
