### ISSUE TITLE
Anforderungen Export-Liste Arbeitsbereiche und Module

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/studio-lite#690]
In der aktuellen Liste wird angezeigt in welchen Arbeitsbereichen und bei wie vielen Aufgaben die folgenden Modul-Versionen verwendet werden: Editor: **iqb-editor-aspect@1.34** Player: **iqb-player-aspect@1.27**. Die Liste verschafft also derzeitig keinen Überblick über andere Modul-Versionen. Vielleicht sollten wir noch einmal zusammen über die Anforderungen an eine solche Liste sprechen. Eine erste grobe Idee: Es werden allen im Studio verwendeten Modul-Versionen aufgelistet inkl. Arbeitsbereich und Aufgabe. Wie gesagt, können da gerne mal gemeinsam drüber sprechen.

**Comment by jojohoch** [comment]
Anzahl der verwendeten Module wird fehlerhaft dargestellt
