### ISSUE TITLE
Aufgabenfolgen: Abmeldung

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/studio-lite#80]
Startet man ein Review via Link, landet man auf der Review-Anmeldeseite und muss dort das Kennwort eingeben um den Review zu starten. Ist der Review gestartet und wird via IQB-Logo beendet, ist eine Reviewliste mit den Reviews zu sehen. Dort befindet sich auch eine Abmeldeschaltfläche. Wir diese betätigt, landet man nicht wie erwartet wieder auf der Review-Anmeldeseite, sondern auf der Studio-Anmeldeseite. Möchte sich eine Person von außerhalb das Review gleich noch einmal ansehen, könnte das verwirrend sein. Diese Person müsste dann den Link noch einmal in die Adresszeile eintragen.

**Comment by tobhu1981** [comment]
Funzt noch nicht so ganz. Habe mal ein Video gemacht, das sollte beschreiben was noch nicht geht.

https://box.hu-berlin.de/f/6de03b4af46541e4b3db/

**Comment by tobhu1981** [comment]
Geht noch nicht. Immer wenn zuvor auf das IQB-Logo geklickt wird bspw. die Aufgabenfolge via IQB-Logo verlassen wird und dann auf das Abmeldezeichen in der Reviewübersicht geklickt wird, landet man nicht wieder bei der Passworteingabe des jeweiligen Reviews, sondern auf der Hauptanmeldeseite des Studios.

**Comment by tobhu1981** [comment]
Geht noch nicht.

**Comment by mechtelm** [comment]
Dieses Feature kann ich nicht implementieren. Das ist kein Fehler, sondern: Das System kann (soll) nicht wissen, ob vor der Abmeldung ein Review ausgeführt wurde. Der Lin kgeht halt verloren, wenn man auf das Logo geht.

Wenn man den Review wieder starten will, muss man halt wieder auf den Link klicken, den man bekommen hat.
